FROM ubuntu:18.04

LABEL version="1.0"
LABEL description="Install any package using SDKMan"

ENV SDKMAN_DIR /root/.sdkman
ENV JAVA_VERSION 25.r25-nik

RUN ["mkdir", "-p", "/apps/home"]
RUN ls -la /apps/home
RUN apt-get update && apt-get install -y zip curl g++ zlib1g-dev libfreetype6-dev
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN curl -s "https://get.sdkman.io" | bash
RUN chmod a+x "$SDKMAN_DIR/bin/sdkman-init.sh"

RUN set -x \
    && echo "sdkman_auto_answer=true" > $SDKMAN_DIR/etc/config \
    && echo "sdkman_auto_selfupdate=false" >> $SDKMAN_DIR/etc/config \
    && echo "sdkman_insecure_ssl=false" >> $SDKMAN_DIR/etc/config

WORKDIR $SDKMAN_DIR
RUN [[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh" && exec "$@"

RUN source /root/.bashrc
RUN source "$SDKMAN_DIR/bin/sdkman-init.sh" && sdk install java $JAVA_VERSION
RUN source "$SDKMAN_DIR/bin/sdkman-init.sh" && sdk install maven
WORKDIR /apps/home

COPY pom.xml .
COPY src ./src
RUN source "$SDKMAN_DIR/bin/sdkman-init.sh" && mvn  -Pnative native:compile

ENTRYPOINT ["./target/testegraalvm"]